version: '3.8'
services:
  frontend:
    build: ./recipe-recommender
    ports:
      - "3000:3000"
    volumes:
      - ./recipe-recommender:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=development
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
