name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Decode and prepare SSL certificates
    - name: Decode SSL Certificates
      run: |
        echo "${{ secrets.KEY_PEM_BASE64 }}" | base64 -d > ./ssl/key.pem
        echo "${{ secrets.CERT_PEM_BASE64 }}" | base64 -d > ./ssl/cert.pem

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_DROPLET_IP }}
        username: ${{ secrets.DO_USERNAME }}
        password: ${{ secrets.DO_PASSWORD }}
        script: |
          cd recipe-recommender
          git pull
          docker-compose up -d --build
